### PR TITLE
Hide old events

### PR DESCRIPTION
**Pull request by Alex-CD**
Hides events on the 'future events' panel, based on their end time.

### CODE REVIEW

**Comment by Alex-CD** [comment]
hmmm. Given that events have an end date & time, could we refactor out is-over?
Were you planning on using this for something?

**Comment by Alex-CD** [comment]
Don't merge this yet, I may as well implement the same fix for the footer 'next event' thingmabob.

**Comment by Alex-CD** [comment]
Ready to merge.

**Comment by crablab** [comment]
Rebased. Waiting for checks to run

**Pull request merged**
